#+title: Forsp tasks
#+filetags: c forsp

* Resources
- Article: https://xorvoid.com/forsp.html
- Repo: https://github.com/xorvoid/forsp
- [[~/Code/ThirdParty/forsp/forsp.c]]
* TODO Do we need better errors?
Currently we use ~FAIL~ to stop on a critical error.  This is used in
parsing - which can be forgiven for hard stops - and the object API.
This is nice, but if we want to introduce more powerful features (like
being able to catch and deal with errors in the actual language) we'll
need a centralised approach to this.  FAIL isn't catchable.

We also need a way to propagate errors through potentially many layers
of recursion - perhaps even adding info at each pass step.
* WIP Parser
** TODO stream_init_cstr
Create a new stream from a CString passed in.  Makes testing easier
and adds an avenue for better testing.
** TODO
* WIP Environments
SCHEDULED: <2025-11-16 Sun>
* TODO Closures
SCHEDULED: <2025-11-17 Mon>
* TODO Primitives
SCHEDULED: <2025-11-17 Mon>
* TODO Compute/evaluate
SCHEDULED: <2025-11-18 Tue>
